import {
  BaseEntity,
  Column,
  CreateDateColumn,
  Entity,
  JoinTable,
  ManyToMany,
  ManyToOne,
  PrimaryGeneratedColumn,
} from "typeorm";
import { Field, ObjectType, ID } from "type-graphql";
import { User } from "./User";
import { Article } from "./Article";

export enum ReservationStatus {
  Pending = "pending",
  Submitted = "submitted",
  Validated = "validated",
  Ongoing = "ongoing",
  Ended = "ended",
}

export enum PaymentStatus {
  Pending = "pending",
  Paid = "paid",
}

@ObjectType() //typeGraphQl
@Entity() //typeORM
export class Reservation extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn()
  id: string;

  // automatically generated by typeOrm
  @Field()
  @CreateDateColumn()
  createdAt: Date;

  @Field()
  @Column()
  startDate: Date;

  @Field()
  @Column()
  endDate: Date;

  @Field()
  @Column()
  status: ReservationStatus;

  @Field({ nullable: true })
  @Column({ nullable: true })
  customerPhone?: string;

  @Field({ nullable: true })
  @Column({ nullable: true })
  customerAddress?: string;

  @Field({ nullable: true })
  @Column({ nullable: true })
  paymentMethod?: string;

  @Field()
  @Column({ default: PaymentStatus.Pending })
  paymentStatus: PaymentStatus;

  @Field(() => User)
  @ManyToOne(() => User, (user) => user.reservations)
  user: User;

  @Field(() => [Article]) // GraphQL
  @ManyToMany(() => Article, (article) => article.reservations) //  TypeORM
  @JoinTable()
  articles: Article[];
}
